package org.moa.moa.presentation.ui.theme

object Strings {
    const val moa = "MOA"
    const val home = "HOME"
    const val calendar = "CALENDAR"
    const val todo = "TO-DO"
    const val user = "MY"
    const val kakaotalk = "카카오톡"
    const val google = "구글"
    const val apple = "애플"
    const val login = "간편 로그인"
    const val continueText = "계속하기"
    const val pleaseEnterId = "닉네임을 작성해주세요"
    const val pleaseEnterId2 = "모아가 닉네임으로 불러줄 거예요!"
    const val enterPlaceholder = "입력해주세요"
    const val pleaseEnterBirthDate = "생일을 입력해주세요"
    const val pleaseEnterBirthDate2 = "모아가 생일이 되면 축하해줄게!"
    const val birthDatePlaceholder = "YYYY.MM.DD"
    const val pleaseEnterGender = "성별을 알려주세요"
    const val pleaseEnterGender2 = "모아가 참고하도록 할게요!"
    const val man = "남성"
    const val woman = "여성"
    const val record = "기록하기"
    const val record_text_guidline1 = "어떤 일이 있었는지"
    const val record_text_guidline2 = "기록해주세요"
    const val text_input_placeholder = "글을 입력해주세요"
    const val image_guideline = "이미지를 추가할 수 있어요"
    const val add_record_text = "조각이 생성되었어요!"
    const val confirm = "확인"
    const val date_time_format = "M.d (E) HH:mm"
    const val retake_picture = "다시 촬영"
    const val write = "글 쓰기"
    const val recording_guidline1 = "소리를"
    const val recording_guidline2 = "녹음해주세요"
    const val start = "시작"
    const val pause = "일시정지"
}